version: '3'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=war
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  server:
    depends_on:
      - db
    build: ./server
    restart: on-failure:10
    ports:
      - 6868:8080
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=war
      - DB_PORT=3306
      - NODE_DOCKER_PORT=8080
    stdin_open: true
    tty: true

volumes: 
  db:
